[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"

[window]
dynamic_padding = true
decorations = "full"
title = "Alacritty"
opacity = 1.0

[window.class]
instance = "Alacritty"
general = "Alacritty"

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 12

[font.normal]
family = "monospace"
style = "Regular"

[font.bold]
family = "monospace"
style = "Bold"

[font.italic]
family = "monospace"
style = "Italic"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[cursor]
style = "Underline"

[general]
live_config_reload = true
import = ["./generated-colors.toml"]
