[config.wallpaper]
command = "awww"
arguments = ["img", "--transition-type", "center"]
set = true

[templates.alacritty]
input_path = './templates/alacritty.toml'
output_path = '~/.config/alacritty/generated-colors.toml'

[templates.btop]
input_path = './templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'
post_hook = 'pkill -SIGUSR2 btop'

[templates.cava]
input_path = './templates/cava'
output_path = '~/.config/cava/themes/matugen'
post_hook = 'pkill -SIGUSR2 cava'

[templates.fuzzel]
input_path = './templates/fuzzel.ini'
output_path = '~/.config/fuzzel/generated-theme.ini'

[templates.mako]
input_path = './templates/mako'
output_path = '~/.config/mako/generated-theme'
post_hook = 'makoctl reload'
