"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Sindre Moen"

[ui]
default-command = "log"
diff-editor = ":builtin"
diff-formatter = ["difft", "--color=always", "$left", "$right"]
editor = "nvim"
pager = ":builtin"

[signing]
backend = "ssh"
behavior = "own"

[jjj.splash]
skip = true

[remotes.origin]
auto-track-bookmarks = "glob:*"
